; Listing generated by Microsoft (R) Optimizing Compiler Version 19.34.31933.0 

	TITLE	C:\Users\user\github\Cpp_Study\Source\Buckland_Chapter7 to 10_Raven\Debug\Goal_SayPhrase.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
